name: Update Stats

on:
  schedule:
    - cron: '0 6 * * *'  # Jeden Tag um 6 Uhr früh (war falsch mit **)
  workflow_dispatch:  # Manuell auslösbar

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Wichtig für push
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Standard Token reicht
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install Dependencies
        run: pip install requests
      
      - name: Run Stats Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Standard Token verwenden
        run: python update_stats.py
      
      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "🤖 Automatisches Update der GitHub Public Stats" || exit 0
          git push
